// BibTeX export for sorted batch items.
//
// Citation keys follow the conventional `{LastName}{Year}` shape with a
// numeric suffix when keys would otherwise collide. Special chars in
// fields get LaTeX-escaped per the BibTeX spec — without this, titles
// like "C# & % usage" produce broken .bib files.
//
// Entry type for everything is `@misc` — we don't have enough metadata
// to distinguish article vs book vs report, and @misc is universally
// accepted by reference managers as a fallback. A future revision could
// inspect file extension + producer + page count to upgrade to @book /
// @techreport / @phdthesis where the signal is strong enough.

export interface BibSource {
    title?: string;
    author?: string;
    year?: string;
    /// Original filename — used as the `note` field so the user can
    /// trace each entry back to its file post-sort.
    filename?: string;
    /// Final post-sort path, when available — also goes into `note` for
    /// traceability.
    path?: string;
}

const PLACEHOLDER_VALUES = new Set([
    'unknown title', 'unknown author', 'unknown year', 'unknown',
    'untitled', 'n/a', 'na', '-', '?', '',
]);

function isMeaningful(v: string | undefined | null): v is string {
    if (!v) return false;
    return !PLACEHOLDER_VALUES.has(v.trim().toLowerCase());
}

/// Extract the last name from "First Last" or "Last, First" style.
/// Falls back to the first whitespace-separated token, then a sanitized
/// "anon" so we always have something for the citation key.
function lastNameFor(author: string | undefined): string {
    if (!isMeaningful(author)) return 'anon';
    const a = author.trim();
    // "Smith, John" → "Smith"
    const comma = a.indexOf(',');
    if (comma > 0) {
        return a.slice(0, comma).trim();
    }
    // "John Q. Smith" → "Smith"
    const tokens = a.split(/\s+/).filter(Boolean);
    return tokens[tokens.length - 1] || 'anon';
}

function sanitizeKey(s: string): string {
    return s
        .normalize('NFKD')
        .replace(/[̀-ͯ]/g, '') // strip combining marks
        .replace(/[^A-Za-z0-9]/g, '')
        || 'item';
}

/// LaTeX-escape a value for inclusion in a `field = {...}` BibTeX entry.
/// Wraps capital letters in {} so BibTeX preserves them in titles.
function escapeBib(s: string, isTitle = false): string {
    let out = s
        .replace(/\\/g, '\\textbackslash{}')
        .replace(/([&%$#_{}])/g, '\\$1')
        .replace(/\^/g, '\\^{}')
        .replace(/~/g, '\\~{}');
    if (isTitle) {
        // Protect capitalization — BibTeX lowercases titles in some
        // styles unless braces guard each capital.
        out = out.replace(/\b([A-Z][a-z]*)\b/g, (_, w) => `{${w}}`);
    }
    return out;
}

export function buildBibEntry(src: BibSource, key: string): string {
    const fields: [string, string][] = [];
    if (isMeaningful(src.title)) fields.push(['title', escapeBib(src.title!.trim(), true)]);
    if (isMeaningful(src.author)) fields.push(['author', escapeBib(src.author!.trim())]);
    if (isMeaningful(src.year)) {
        // Strip everything after the first 4-digit year — handles values
        // like "2023-03" or "approx. 2019".
        const m = src.year!.match(/\d{4}/);
        if (m) fields.push(['year', m[0]]);
    }
    const noteParts: string[] = [];
    if (src.filename) noteParts.push(src.filename);
    if (src.path && src.path !== src.filename) noteParts.push(src.path);
    if (noteParts.length) fields.push(['note', escapeBib(noteParts.join(' — '))]);

    if (fields.length === 0) {
        // Even an empty entry is preferable to skipping silently — the
        // user can fix it in their reference manager.
        fields.push(['title', '{Unknown}']);
    }

    const body = fields.map(([k, v]) => `  ${k} = {${v}}`).join(',\n');
    return `@misc{${key},\n${body}\n}`;
}

/// Build a complete .bib document from a list of sources. Citation keys
/// are stable (deterministic on input order) and unique — duplicates get
/// a numeric suffix.
export function buildBibFile(sources: BibSource[]): string {
    const seen = new Map<string, number>();
    const entries: string[] = [];
    for (const src of sources) {
        const ln = sanitizeKey(lastNameFor(src.author));
        const yr = isMeaningful(src.year) ? (src.year!.match(/\d{4}/)?.[0] ?? 'nodate') : 'nodate';
        const base = `${ln}${yr}`;
        const n = (seen.get(base) ?? 0) + 1;
        seen.set(base, n);
        const key = n === 1 ? base : `${base}_${n}`;
        entries.push(buildBibEntry(src, key));
    }
    const header = `% Generated by CrispSorter\n% ${new Date().toISOString()}\n% ${sources.length} entries\n\n`;
    return header + entries.join('\n\n') + '\n';
}
